[project]
authors = ["Daniel Olds <dpolds@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "map_maker"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.6,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.3,<4"
streamlit = "==1.40.0"

[pypi-dependencies]
streamlit-drawable-canvas = ">=0.9.3"
